# several key selective parameters
data_dir: './data' #dir to load data
output_dir: './output' #dir to save output

# word embedding
embedding_path: './data/glove/glove.6B.100d.txt' #pre_trained word embedding
word_dim: 100 #dimension of word embedding

# train settings
model_name: CR-CNN #model name
mode: 1 #[0, 1]  running mode: 1 for training; otherwise testing
seed: 9918 #random seed
cuda: 0 #num of gpu device, if -1, select cpu
epoch: 20 #max epoches during training

# hyper parameters
dropout: 0.5 #the possiblity of dropout
batch_size: 128 #batch size
lr: 1.0 #learning rate
max_len: 100 #max length of sentence
pos_dis: 50 #max distance of position embedding
pos_dim: 70 #dimension of position embedding


# hyper parameters for cnn
filter_num: 1000 #the number of filters in convolution
window: 3 #the size of window in convolution

margin_positive: 2.5 #positive margin in the CRCNN loss function
margin_negative: 0.5 #negative margin in the CRCNN loss function
gamma: 2.0 #scaling factor `gamma` in the CRCNN loss function
L2_decay: 1e-3 #L2 weight decay
